const DEVICE_NAME = "TUTUM";

const PAIRING_PIN = '0216';

const COUNT_START = 0;
const SIGN_START = [0xFF, 0xFF, 0xFF, 0xFE];
const LENGTH_START = 1;

enum SENSOR_TYPE {
  IMU,
  MAG,
  CAPACITY,
  TEMPERATURE,
  OXYGEN,
}

const DATA_LENGTH = {
  SENSOR_TYPE.IMU: LENGTH_IMU,
  SENSOR_TYPE.MAG : LENGTH_MAG,
  SENSOR_TYPE.CAPACITY: LENGTH_CAPACITY,
  SENSOR_TYPE.TEMPERATURE: LENGTH_TEMPERATURE,
  SENSOR_TYPE.OXYGEN: LENGTH_OXYGEN,
};

const COUNT_TEMPERATURE = 792*4+4;
const LENGTH_TEMPERATURE = 4;

const COUNT_IMU_NEXT_TEMPERATURE = 792*4+5;

const COUNT_CAPACITY = 792*4+6;
const LENGTH_CAPACITY = 4;

const COUNT_MAG_NEXT_CAPACITY = 792*4+7;

const COUNT_IMU_NEXT_CAPACITY = 792*4+8;

const COUNT_OXYGEN = 792*4+9;
const LENGTH_OXYGEN = 4;

const COUNT_IMU_START = 1;
const LENGTH_EACH_IMU = 2;
const LENGTH_IMU = LENGTH_EACH_IMU * 6;
const LENGTH_MAG = LENGTH_EACH_IMU * 3;


enum DIRECTION { UNKNOWN, IN_OUT, OUT_IN }
